// packages/create-spve/templates/lit-ts/src/main.ts
import type { SPFI } from '@pnp/sp'
import type { SpveModule } from 'spve'
import { initializeSP } from 'spve/internal/runtime'
import { nothing, render } from 'lit'
import { App, type AppProps } from './App'
import './style.css'

interface Services {
  sp: SPFI
}

const application: SpveModule<AppProps, Services> = {
  mount({ element, props, services }) {
    initializeSP(services.sp)
    let currentProps = { ...props }

    const update = () => render(App(currentProps), element)
    update()

    return {
      setProps(next) {
        currentProps = { ...next }
        update()
      },
      unmount: () => render(nothing, element),
    }
  },
}

export default application

// packages/create-spve/templates/react-ts/src/main.ts
import type { SPFI } from '@pnp/sp'
import type { SpveModule } from 'spve'
import { initializeSP } from 'spve/internal/runtime'
import { createElement } from 'react'
import { createRoot } from 'react-dom/client'
import { App, type AppProps } from './App'
import './style.css'

interface Services {
  sp: SPFI
}

const application: SpveModule<AppProps, Services> = {
  mount({ element, props, services }) {
    initializeSP(services.sp)
    const root = createRoot(element)
    let currentProps = { ...props }

    const render = () => root.render(createElement(App, currentProps))
    render()

    return {
      setProps(next) {
        currentProps = { ...next }
        render()
      },
      unmount: () => root.unmount(),
    }
  },
}

export default application
