// packages/create-sp/templates/lit-ts/src/main.ts
import { initializeSP, type SpveApp } from 'spve'
import { nothing, render } from 'lit'
import { App } from './App'
import './style.css'

const app: SpveApp = {
  mount({ element, props, services }) {
    initializeSP(services.sp)
    render(App(props), element)

    return {
      setProps: (next) => render(App(next), element),
      unmount: () => render(nothing, element),
    }
  },
}

export default app

// packages/create-spve/templates/react-ts/src/main.ts
import { initializeSP, type SpveApp } from 'spve'
import { createElement } from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './App'
import './style.css'

const app: SpveApp = {
  mount({ element, props, services }) {
    initializeSP(services.sp)
    const root = createRoot(element)

    root.render(createElement(App, props))

    return {
      setProps: (next) => root.render(createElement(App, next)),
      unmount: () => root.unmount(),
    }
  },
}

export default app
