// packages/create-spve/templates/svelte-ts/src/App.svelte
<script lang="ts">
  import type { Readable } from 'svelte/store'
  import type { AppProps } from 'spve/client'

  let { properties }: { properties: Readable<AppProps> } = $props()
  const title = __TITLE_JS__
</script>

<main class="spve-app">
  <h1>{title}</h1>
  {#if $properties.description}
    <p>{$properties.description}</p>
  {/if}
</main>

// packages/create-spve/templates/lit-ts/src/App.ts
import { html, type TemplateResult } from 'lit'
import type { AppProps } from 'spve/client'

const title = __TITLE_JS__

export function App({ description }: AppProps): TemplateResult {
  return html`
    <main class="spve-app">
      <h1>${title}</h1>
      ${description ? html`<p>${description}</p>` : null}
    </main>
  `
}
